### ISSUE TITLE
Cannot input anything in the fields of WebView

### ISSUE THREAD

**Issue by SinoAHpx** [OutSystems/WebView#342]
![image](https://github.com/OutSystems/WebView/assets/34391004/aec5318f-7576-4240-8a8c-8632237efcfa)
This is a window simply comprised of a `WebView` control, I tried to input anything to the field but nothing appears. When I hit right click, there's a context menu poped on the edge of screen abnormally:
![image](https://github.com/OutSystems/WebView/assets/34391004/5a8685f6-df2b-463e-b1e4-a70a3dafb492)

**Comment by joaompneves** [comment]
Have you tried on the [Sample App](https://github.com/OutSystems/WebView/tree/master/SampleWebView.Avalonia)? Is your control Focusable?

**Comment by SinoAHpx** [comment]
![Uploading image.png…]()
Actually I can't even run it

**Comment by joaompneves** [comment]
There's a manifest missing (on windows). We'll open a PR to fix it.

**Comment by joaompneves** [comment]
Meanwhile you can check and apply the same changes of: https://github.com/OutSystems/CefGlue/pull/143/files

**Comment by fmgracias** [comment]
Hey @SinoAHpx , we've merged the fix to master.
Thanks for reporting

**Comment by SinoAHpx** [comment]
Glad to be of help :)
But unfortunately, my issue still exists, even though the sample works well.
